# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install 
    npm test
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)/WebApp'
  

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students (4b5349a8-42be-456a-a12d-efd2af804472)'
    appType: 'webAppLinux'
    appName: 'dominikwukovatznodeappryksmby4kranq'
    package: '$(System.DefaultWorkingDirectory)/WebApp'
    customWebConfig: '-Handler iisnode -NodeStartFile index.js -appType node'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    searchFolder: '$(Build.SourcesDirectory)/WebApp'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/WebApp'
    