version: "3.9"
    
services:
  db:
    build: ./MySQL
    image: mysqlimage
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    depends_on:
      - db

    build: ./Wordpress
    image: mywordpressimage
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
volumes:
  db_data: {}
  wordpress_data: {}

